### ISSUE TITLE
New sequence for round state and player state

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/housinggame-common#7]
Selling houses (to the bank) needs to take place before buying houses (available in the round, from the bank or from another player VIA the bank).

**Comment by averbraeck** [comment]
The (simplified) flow is then as follows:

- Faciliatator logs in, LOGIN state
- Player logs in, LOGIN state (wait screen till player starts round)

- Facilitator clicks new round, NEW_ROUND state
- Player can move to budget screen, READ_BUDGET state

- Facilitator allows news read, ANNOUNCE_NEWS state
- Player can move to news screen, READ_NEWS state

- Facilitator allows checking of houses, CHECK_HOUSE state
- Players can view the houses, VIEW_HOUSE state

- Facilitator allows selling of houses (round 2 and up, not in round 1), SELL_HOUSES state; players makes the choice to either sell their house, or stay in their current house, and the facilitator confirms the choices (price, moving reason) in the facilitator screen.
- Players can choose to stay or sell their house (round 2 and up), SELL_HOUSE state. When a player sells the house, the sales price is entered by the player (and checked and possibly corrected by the facilitator).
- After the player has confirmed their choice, the app WAITS till the facilitator moved forward. The state is SELL_HOUSE_WAIT (this could have its own screen).
- While waiting, the player can scroll through the accordion. 
- 
- Facilitator allows buying of houses (round 1 and up), BUY_HOUSES state; players who don't own a house have to buy a new house, and the facilitator confirms the choices (price) in the facilitator screen.
- Players who do not own a house have to buy a house (round 1 and up), BUY_HOUSE state. When a player buys a house, the buying price is entered by the player (and checked and possibly corrected by the facilitator).
- After the player has confirmed their choice, the app WAITS till the facilitator moved forward. The state is BUY_HOUSE_WAIT (this could have its own screen).
- A player who stays in their house might move immediately to the BUY_HOUSE_WAIT state and skip the SELL_HOUSE_WAIT state, since they cannot buy a new house anyhow. 
- While waiting, the player can scroll through the accordion. 

- After the buying/selling is completed, the facilitator can calculate taxes per community. CALCULATE_TAXES state
- Players can view the taxes with explanation. VIEW_TAXES state

- The facilitator allows players to buy improvements. ALLOW_IMPROVEMENTS state
- The player can buy improvements, BUY_IMPROVEMENTS state. The player can only press 'confirm' when the next screen is opened.

- The facilitator opens the survey, SHOW_SURVEY state
- The player fills in the survey, ANSWER_SURVEY state

- The facilitator rolls the dice and enters the results in the facilitator screen, ROLL_DICE state
- The player views the damage as a result of the pluvial/fluvial flooding, VIEW_DAMAGE state

- The facilitator allows players to see a round summary, SHOW_SUMMARY state
- The player views the summary, VIEW_SUMMARY state
- After this, the player waits till the next round is opened by the facilitator

**Comment by averbraeck** [comment]
A flowchart with the interactions is shown in the flowchart below:

[UI-flowchart.pdf](https://github.com/averbraeck/housinggame-common/files/13538995/UI-flowchart.pdf)

**Comment by averbraeck** [comment]
After the exploration of house properties using the sheets and the board, as well as the viewing of affordability of houses on the phone and bidding, the facilitator can allow the players to enter the data om their phone.
- The facilitator status changes to `ALLOW_BUYING` in round 1, and `ALLOW_SELLING` in rounds 2 and up.
- The player **stays in the state** `VIEW_HOUSES` till they press the `BUY HOUSE`, `SELL HOUSE` or `STAY` button on their screen.
- After pressing `BUY HOUSE` button, the player moves into the `BUY_HOUSE_WAIT` state to allow the facilitator to approve or reject the buy.
- After pressing the `SELL HOUSE` button, the player moves into the `SELL_HOUSE_WAIT` state to allow the facilitator to approve or reject the sell.
- After pressing the `STAY` button, the player moves into the `STAY_HOUSE_WAIT` state. Also here, the facilitator can approve or reject, to correct a mistakingly pressed `STAY` button by the player.

**Comment by averbraeck** [comment]
The sell in rounds 2 and up is followed by a buy that works exactly the same as the one in round 1.

**Comment by averbraeck** [comment]
The wait state for selling, buying, or staying can have TWO possible outcomes: either the facilitator approves the buy/sell/stay, or the facilitator rejects the buy/sell/stay. The button at the bottom of the buy/sell/stay wait screen of the player's phone has to change accordingly:
- The greyed out button on the `sell-house-wait` screen is `BUY HOUSE`, since the next step of the player after an approved sale is buying a house. This button is either turned blue (sale approved) or changes into a red `REJECTED: GO BACK` button. The blue button takes the player to the `buy-house` screen, where the player can view the houses to buy again. The `GO BACK` button brings the player back to the `sell-house` screen, and the player state is changed accordingly.
- The greyed out button on the `stay-house-wait` screen is `PAY TAXES`, since the next step of the player after staying in is paying the taxes. This button is either turned blue (stay approved) or changes into a red `REJECTED: GO BACK` button. The blue button takes the player to the `pay-taxes` screen, where the player can pay the appropriate taxes The `GO BACK` button brings the player back to the `sell-house` screen, and the player state is changed accordingly.
- The greyed out button on the `buy-house-wait` screen is `PAY TAXES`, since the next step of the player after staying in is paying the taxes. This button is either turned blue (buy approved) or changes into a red `REJECTED: GO BACK` button. The blue button takes the player to the `pay-taxes` screen, where the player can pay the appropriate taxes The `GO BACK` button brings the player back to the `buy-house` screen, and the player state is changed accordingly.

**Comment by averbraeck** [comment]
The latest flowchart incorporating all the above is included below:

[20231206_UI-flowchart.pdf](https://github.com/averbraeck/housinggame-common/files/13608353/20231206_UI-flowchart.pdf)

**Comment by averbraeck** [comment]
These are now the player states:

```java
    /** Logged in. PlayerRound record has NOT yet been created for the round, waiting for permission to proceed. */
    LOGIN(10),

    /** PlayerRound record for the new round has been created. Player can read their budget. */
    READ_BUDGET(20),

    /** View the news screen. */
    READ_NEWS(30),

    /** View the houses (available in round and owned by other players). */
    VIEW_HOUSES(40),

    /** Waiting screen after selling the house -- wait till all players are done. */
    SELL_HOUSE_WAIT(50),

    /** Waiting screen after staying in the house -- wait till all players are done. */
    STAY_HOUSE_WAIT(55),

    /** View the houses (available in round and sold by other players); decide on buying a house. */
    BUY_HOUSE(60),

    /** Waiting screen after buying the house -- wait till all players are done. */
    BUY_HOUSE_WAIT(70),

    /** Information on the financial and satisfaction status after buying a (new) house. */
    BOUGHT_HOUSE(80),

    /** Information on the financial and satisfaction status after staying in the current house. */
    STAYED_HOUSE(85),

    /** View the result of tax payment on the spendable income. */
    PAID_TAXES(90),

    /** Allow buying and selling of improvements (after taxes have been paid). */
    BUY_IMPROVEMENTS(100),

    /** Answer the questions of the survey. */
    ANSWER_SURVEY(110),

    /** Survey has been completed. */
    SURVEY_COMPLETED(120),

    /** View the damage and effect on spendable income after the dice rolls. */
    VIEW_DAMAGE(130),

    /** View the summary screen and wait for the facilitator to proceed to the next round (if available). */
    VIEW_SUMMARY(140);
```

**Comment by averbraeck** [comment]
The facilitator state `CALCULATE_TAXES` has been changed into `CALCULATED_TAXES` (it has happened when the facilitator reaches this state).

All numbers in tens correspond between the facilitator state and the player state.

**Comment by vjcortesa** [comment]
**Regarding the states for the player:** 
BUY_HOUSE -> VIEW_BUY_HOUSES_ The action the player is doing is about viewing the houses to buy until the player presses the button BUY HOUSES then the state changes to BUY_HOUSE_WAIT

**Comment by averbraeck** [comment]
Made some simplifications in the game flow.

[20231208_UI-flowchart.pdf](https://github.com/averbraeck/housinggame-common/files/13612860/20231208_UI-flowchart.pdf)

**Comment by averbraeck** [comment]
New round states:

```java
    /** Logged in, GroupRecord created, waiting for sufficient number of players to log in. */
    LOGIN(10),

    /** Sufficient number of players logged in, allow players to look at their budget. */
    NEW_ROUND(20),

    /** Allow players to read the news. */
    ANNOUNCE_NEWS(30),

    /** Show available houses to players for selling/buying (rounds 2 and up) or just buying (round 1). */
    SHOW_HOUSES(40),

    /** Enabled the decision on selling house or staying (from round 2 onward). */
    ALLOW_SELLING(50),

    /** Indicate that selling is finished, all players have indicated 'STAY' or 'SELL HOUSE'. */
    SELLING_FINISHED(60),

    /** Enabled the decision which house to buy (only for players who do not own a house). */
    ALLOW_BUYING(70),

    /** Indicate that buying is finished, all active players own a house. */
    BUYING_FINISHED(80),

    /** Allow the players to view and buy the improvements. */
    ALLOW_IMPROVEMENTS(90),

    /** Open the survey questions. */
    SHOW_SURVEY(100),

    /** Sufficient number of players have completed the survey. Close the survey to allow dice rolling. */
    SURVEY_COMPLETED(110),

    /** When all players have completed the survey, the dice rolls can be entered; players can view damage. */
    ROLLED_DICE(120),

    /** Open the summary view for the players. */
    SHOW_SUMMARY(130);

    /** After this, next round (if available) can be clicked, which moves the state to NEW_ROUND. */
```

**Comment by averbraeck** [comment]
New player states:

```java
    /** Logged in. PlayerRound record has NOT yet been created for the round, waiting for permission to proceed. */
    LOGIN(10),

    /** PlayerRound record for the new round has been created. Player can read their budget. */
    READ_BUDGET(20),

    /** View the news screen. */
    READ_NEWS(30),

    /** View the houses (available in round and owned by other players). */
    VIEW_SELL_HOUSES(40),

    /** Waiting screen after selling the house -- wait till all players are done. */
    SELL_HOUSE_WAIT(50),

    /** Waiting screen after staying in the house -- wait till all players are done. */
    STAY_HOUSE_WAIT(55),

    /** View the houses (available in round and sold by other players); decide on buying a house. */
    VIEW_BUY_HOUSE(60),

    /** Waiting screen after buying the house -- wait till all players are done. */
    BUY_HOUSE_WAIT(70),

    /** Information on the financial and satisfaction status after buying a (new) house. */
    BOUGHT_HOUSE(80),

    /** Information on the financial and satisfaction status after staying in the current house. */
    STAYED_HOUSE(85),

    /** Allow buying and selling of improvements (after taxes have been paid). */
    VIEW_IMPROVEMENTS(90),

    /** Answer the questions of the survey. */
    ANSWER_SURVEY(100),

    /** Survey has been completed. */
    SURVEY_COMPLETED(110),

    /** View the damage and effect on spendable income after the dice rolls. */
    VIEW_DAMAGE(120),

    /** View the summary screen and wait for the facilitator to proceed to the next round (if available). */
    VIEW_SUMMARY(130);
```

**Comment by averbraeck** [comment]
Updated game flow with some final textual changes:

[20231208_UI-flowchart.pdf](https://github.com/averbraeck/housinggame-common/files/13613067/20231208_UI-flowchart.pdf)

**Comment by averbraeck** [comment]
Based on Issue #13, the state chart has been slightly adapted:

[20231210_UI-flowchart.pdf](https://github.com/averbraeck/housinggame-common/files/13627558/20231210_UI-flowchart.pdf)
